PucWebApplication/Controllers/ResultadoController.cs
using Microsoft.AspNetCore.Mvc;
using PucWebApplication.Data;

namespace PucWebApplication.Controllers
{

    // Controlador da Pasta Resultado //
    public class ResultadoController : Controller
    {
        private readonly Contexto _context;

        public ResultadoController(Contexto context)
        {
            _context = context;
        }
        public IActionResult Pesquisa(Models.Usuario c, string Pesquisa = "")
        {
            var q = _context.Usuario.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisa))
            {
                q = q.Where(c => c.Bairro.Contains(Pesquisa));
                q = q.OrderBy(c => c.Nome);


                return View(q.ToList());

            }
            return View(_context.Usuario.ToList());
        }
    }

    // Fim Controlador da Pasta Resultado //

}

PucWebApplication/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Org.BouncyCastle.Crypto.Generators;
using PucWebApplication.Data;
using PucWebApplication.Models;

namespace PucWebApplication.Controllers
{

    public class UsuariosController : Controller
    {
        private readonly Contexto _context;
        private string caminhoServidor;
        
        private readonly IWebHostEnvironment webHostEnvironment;


        public UsuariosController(Contexto context, IWebHostEnvironment sistema, IWebHostEnvironment hostEnvironment, Contexto _contexto)
        {
            _context = context;
            caminhoServidor = sistema.WebRootPath;
            webHostEnvironment = hostEnvironment;
        }

        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> login([Bind("Id,Email,Senha")] Usuario usuario)
        {
            var user = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Email == usuario.Email);

            if (user == null)
            {
                ViewBag.Message = "Usuário e/ou Senha inválidos!";
                return View();
            }

            bool isSenhaOk = BCrypt.Net.BCrypt.Verify(usuario.Senha, user.Senha);

            if (isSenhaOk)
            {

                var claims = new List<Claim> {
                    new Claim(ClaimTypes.Name, user.Nome),
                    new Claim(ClaimTypes.NameIdentifier, user.Nome),
                    new Claim(ClaimTypes.Role, user.Perfil.ToString())
                };

                var userIdentity = new ClaimsIdentity(claims, "Login");

                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                var props = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    ExpiresUtc = DateTime.Now.ToLocalTime().AddDays(7),
                    IsPersistent = true
                };

                await HttpContext.SignInAsync(principal, props);


                return Redirect("/Home");
            }

            ViewBag.Message = "Usuário e/ou Senha inválidos!";
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        //Subir Imagens do Usuário
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Upload(IFormFile foto)
        {
            string caminhoParaSalvaImagem = caminhoServidor + "\\ImagensUsuarioUpload\\";
            string novoNomeParaImage = Guid.NewGuid().ToString() + "__________" + foto.FileName;
            if (!Directory.Exists(caminhoParaSalvaImagem))
            {
                Directory.CreateDirectory(caminhoParaSalvaImagem);
            }

            using (var stream = System.IO.File.Create(caminhoParaSalvaImagem + novoNomeParaImage))
            {
                foto.CopyToAsync(stream);
            }
            return RedirectToAction("Upload");
        }

        // GET: Usuarios
        public IActionResult Index(string Pesquisa = "")
        {
            var q = _context.Usuario.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisa))
            {
                q = q.Where(c => c.Bairro.Contains(Pesquisa));
                q = q.OrderBy(c => c.Nome);


                return View(q.ToList());

            }

            return View(_context.Usuario.ToList());
        }

        //backup
        //public async Task<IActionResult> Index() {
        //    return View(await _context.Usuario.ToListAsync());
        //}

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        public IActionResult MeuPerfil()
        {
            return View();
        }

        // GET: Usuarios/Create

        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Email,cpf,Idade,cep,Rua,Numero,Complemento,Bairro,Cidade,Senha,Perfil")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Senha = BCrypt.Net.BCrypt.HashPassword(usuario.Senha);
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(login));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Nome == id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Email,cpf,Idade,cep,Rua,Numero,Complemento,Bairro,Cidade,Senha,Perfil")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    usuario.Senha = BCrypt.Net.BCrypt.HashPassword(usuario.Senha);
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Usuario == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Usuario == null)
            {
                return Problem("Entity set 'Contexto.Usuario'  is null.");
            }
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuario.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuario.Any(e => e.Id == id);
        }

        // GET: novo cadastro
        public IActionResult Cadastro()
        {
            return View();
        }

        // POST: UsuarioUploadImg/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cadastro([Bind("Id,Nome,Email,cpf,Idade,cep,Rua,Numero,Complemento,Bairro,Cidade,Senha,Perfil,tel,EmpPhotoPath,EmpFileName")] Usuario usuario, Usuario empdetails)
        {       


            if (ModelState.IsValid)
            {
                usuario.Senha = BCrypt.Net.BCrypt.HashPassword(usuario.Senha);                
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(login));

            }            


            return View(usuario);
            //if (empdetails.ImageFile != null) {
            //    string ImageUploadedFolder = Path.Combine

PucWebApplication/Views/Resultado/Pesquisa.cshtml
@model IEnumerable<PucWebApplication.Models.Usuario>
@{
    ViewData["Title"] = "login";
    ViewData["Title"] = "index";
}

<!DOCTYPE html>
<HTML>

<head>
    <title>Minha Faxina - Resultado de Pesquisa</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Configuração de Media Query -->

    <!-- Fim Configuração de Media Query -->
    <!-- Configurando Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/owl.carousel.min.css">
    <link rel="stylesheet" href="../css/owl.theme.default.min.css">
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <!-- Fim da Configuracao Bootstrap -->
    <!-- Configuração Style -->
    <link rel="stylesheet" href="/css/Pesquisa.css">
    <link href="grid/simple-grid.min.css" rel="stylesheet">
    <!-- Fim Configuração Style -->
</head>

<body data-bs-spy="scroll" data-bs-target=".navbar" data-bs-offset="100">


    <!-- TOP NAV -->
    <div class="top-nav" id="home">
    </div>

    <!-- MENU NAV -->
    <nav class=" navbar-expand-lg navbar-light bg-white sticky-top">
        <div class="navbar container">
             <a asp-controller="Home" asp-action="Index"><img src="/Imagens/Logo.jpg" class="logo"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Inicio</a> 
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Sobre</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Faxineiros</a>
                    </li>
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="nav-item usuario">
                        <div class="dropdown">
                            <button class="usuario dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Olá, @User.Identity.Name
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item first-item" href="#">Meu Perfil</a></li>
                                <li><a asp-controller="Usuarios" asp-action="Logout" class="dropdown-item last-item">Sair</a></li>
                            </ul>
                        </div>
                    </div>
                }
                else
                {
                    <div class="nav-item usuario" style="display: none;">
                        <button data-bs-toggle="modal" data-bs-target="#exampleModal" class="botao">
                            Login
                        </button>
                    </div>
                }

            </div>

        </div>
        <div>
            <div class="col-auto pesquisa">
                @using (Html.BeginForm("Pesquisa", "Resultado", FormMethod.Get))
                {
                    <input type="text" name="Pesquisa" placeholder="Pesquise por nome, endereço ou CEP">
                    <input type="submit" value=" " class="botao-pesquisa" />
                }
            </div>
        </div>
    </nav>

    <div style="display: none">
                    @Html.DisplayNameFor(model => model.Nome)

                    @Html.DisplayNameFor(model => model.Idade)

                    @Html.DisplayNameFor(model => model.Bairro)

                    @Html.DisplayNameFor(model => model.Cidade)

                    @Html.DisplayNameFor(model => model.Complemento)
    </div>
    <div class="row">
            @foreach (var item in Model)
            {
                <div class="card" style="width: 18rem;">
                <img src="@Url.Content("~/UploadedImages/" + item.EmpFileName)" class="card-img-top" style="width:263px; height: 263px; margin-top:10px;" height="120px" width="120px" />
                    <div class="card-body">
                <h5 class="card-title"> @Html.DisplayFor(modelItem => item.Nome)</h5>
                    </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"> <b>Idade:</b> @Html.DisplayFor(modelItem => item.Idade) </li>

                <li class="list-group-item"> <b>Cidade:</b> @Html.DisplayFor(modelItem => item.Cidade) </li>

                <li class="list-group-item"> <b>Bairro:</b> @Html.DisplayFor(modelItem => item.Bairro) </li>
            </ul>
            <div >
                    <a class="btn first" href="@Url.Content("https://wa.me/" + "55" + item.Complemento)"> Entrar em Contato</a>
            </div>
            </div>
            }
            
    </div>
</body>
</HTML>